#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace hydramarker
{
    /*
     * Result of matching a local binary patch against the global marker field.
     *
     * x, y:
     *   Top-left position of the matched patch in the global marker field.
     *
     * rotation_deg:
     *   Rotation that had to be applied to the local patch so that it matched
     *   the global field. Supported values are 0, 90, 180 and 270 degrees.
     */
    struct PatchMatch
    {
        int x = -1;
        int y = -1;
        int rotation_deg = 0;
    };

    /*
     * Global HydraMarker binary field.
     *
     * The field stores the generated global binary marker pattern. Later in the
     * tracking pipeline, the image is converted into local binary k x k patches.
     * These patches are searched in this global field to recover:
     *
     *   - global marker position
     *   - local patch orientation
     *
     * This class is independent of image processing. It only performs lookup in
     * the binary marker field.
     */
    class MarkerField
    {
    public:
        MarkerField() = default;

        /*
         * Load a marker field from a .field file generated by the HydraMarker
         * generator.
         */
        static MarkerField loadFromFile(const std::string& path);

        int width() const { return width_; }
        int height() const { return height_; }
        int patchSize() const { return patch_size_; }

        bool empty() const { return field_.empty(); }

        /*
         * Read one binary value from the global marker field.
         */
        uint8_t at(int x, int y) const;

        /*
         * Extract a k x k patch from the global marker field.
         *
         * x, y define the top-left patch position in global field coordinates.
         */
        std::vector<uint8_t> getPatch(int x, int y) const;

        /*
         * Search a local k x k binary patch in the global marker field.
         *
         * The patch is tested in all four rotations:
         *   0, 90, 180 and 270 degrees.
         */
        std::vector<PatchMatch> findPatch(
            const std::vector<uint8_t>& patch
        ) const;

    private:
        int width_ = 0;
        int height_ = 0;
        int patch_size_ = 0;

        // Row-major storage:
        // field_[y * width_ + x]
        std::vector<uint8_t> field_;

    private:
        /*
         * Check whether a local patch matches the global field at a specific
         * position and rotation.
         */
        bool patchEqualsAt(
            const std::vector<uint8_t>& patch,
            int field_x,
            int field_y,
            int rotation_deg
        ) const;

        /*
         * Read one value from the local patch after applying a virtual rotation.
         *
         * The patch itself is not copied or physically rotated.
         */
        uint8_t patchValueRotated(
            const std::vector<uint8_t>& patch,
            int x,
            int y,
            int rotation_deg
        ) const;
    };

} // namespace hydramarker